---
fail_fast: false
repos:
  - repo: https://github.com/standard/standard
    rev: v17.0.0
    hooks:
      - id: standard
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [css, json, html]
